### ISSUE TITLE
would be great in an emacs ebook reader

### ISSUE THREAD

**Issue by gambhiro** [Fuco1/justify-kp#2]
This looks like an excellent lib!

There are some old ebook packages around ([etxt.el](https://www.emacswiki.org/emacs/etxt.el), [bread.el](https://github.com/dminaev/dot.emacs/blob/master/bread.el)). This lib would get much more exposure if it was part of an ebook (or plain text novels from Gutenberg) reader interface.

I know I would want to read ebooks in emacs :)

**Comment by Fuco1** [comment]
Indeed, that was my original motivation.  Since then I've got an ebook reader and the project never got the time it needed.

I've rewritten this package two times already to make it faster and simpler to use, and I would be willing to help with adding API for use in a reader, but I don't have time to write the reader itself now.

If you want to integrate with some older packages, you're welcome to ask for any changes necessary, I'll try to figure something out.

**Comment by gambhiro** [comment]
It's beyond me, but perhaps someone will get here by googling `emacs ebook reader`. Kudos for the code!

**Comment by wasamasa** [comment]
I'd be somewhat interested in porting [teapub](https://github.com/wasamasa/teapub) to Emacs by leveraging eww.  No idea how well this would integrate into it though...

**Comment by wasamasa** [comment]
More than a year afterwards, [I did it](https://github.com/wasamasa/nov.el) and [figured out how to make use of this package](https://github.com/wasamasa/nov.el/commit/6e29ee309c7f323a446034ea4fefb400b16199e3).  It's not perfect, but makes the text a lot easier to read.  I might open an issue or two to address these.

**Comment by Fuco1** [comment]
You should add a screenshot or two comparing the outputs.

**Comment by gambhiro** [comment]
@wasamasa I'm speechless!

**Comment by wasamasa** [comment]
[Done](https://github.com/wasamasa/nov.el/commit/ec322b439108ffb69ee0010944d4eb502c9f13d5)
